### ISSUE TITLE
Maybe we can have another cloudletexecution listener

### ISSUE THREAD

**Issue by stevenwong1227** [manoelcampos/cloudsim-plus#162]
Having a cloudlet listener is excellent, however when I found out the cloudlet execution class file from cloudsim original file. I found out that the cloudlet execution class file have keeps track of the time for all activities in the Datacenter for a specific Cloudlet.
Include one method called finalizeCloudlet, which  finalizes all relevant information before exiting the Datacenter entity. This method sets the final data of:
1.Wall clock time, i.e. the time of this Cloudlet resides in a Datacenter (from arrival time until departure time).
2.Actual CPU time, i.e. the total execution time of this Cloudlet in a Datacenter.
3.Cloudlet’s finished time so far

Maybe we can combine the cloudlet, cloudlet vm listener and with this cloudlet execution listener together as the cloudlet processing seem to related with all of this three classes. My opinion on this issue.

**Comment by stevenwong1227** [comment]
Maybe we can combine the cloudlet, cloudlet vm listener and with this cloudlet execution listener together as the cloudlet processing seem to related with all of this three classes. My opinion on this issue.

**Comment by manoelcampos** [comment]
Hello Steven, thanks for your suggestion.
This CloudletExecution class is the CloudSim's ResCloudlet class. It is a bit messy and tracks the execution of a Cloudlet in different datacenters. However, neither CloudSim Plus or CloudSim supports Cloudlet migration. This way, it's not possible for a Cloudlet to start at a Datacenter and be migrated to another one. There is even a TODO note in the CloudletExecution class about that.

Anyway, in order to conform to the [Interface Segregation Principle (ISP)](https://en.wikipedia.org/wiki/Interface_segregation_principle), the goal is to have a greater number of small classes with specific responsibilities ([Single Responsibility Principle, SRO](https://en.wikipedia.org/wiki/Single_responsibility_principle)) than a small number of huge classes with lots of responsibilities. That is why we shouldn't merge such classes. 

That reduces classes complexity, improves maintainability and makes it easier to test.
I hope it's clear and thanks for the participating.

**Comment by stevenwong1227** [comment]
Thanks for the information!
