### ISSUE TITLE
Cloudlets don't finish, although the cpu utilization is high

### ISSUE THREAD

**Issue by CharafeddineMechalikh** [manoelcampos/cloudsim-plus#226]
Hello,
I tried to upgrade my simulator (PureEdgeSim) from CloudSim plus 3.0.1 to the latest version.
the simulation  get executed, however, the execution time was negative (cloudlet.getActualCPUtime()).

It turned out that the status of all cloudlets is INEXE and the reason is that no host is suitable for the VMS.

When I change the version of CloudSim Plus to 4.3.0 or lower, everything works fine and all the cloudlets get executed successfully. But when trying a higher version I get that error, without changing anything else (just the version number in pom.xml file).
On the other hand, despite reporting that all the cloudlets are not executed, the cpu utilization is high. which means they are executed?

For now, I just upgraded to 4.3.0, which is the version that worked fine. until I find a workaround or something.
To reproduce the issue,  you can pull PureEdgeSim and try different CloudSim Plus versions.

Thank you very much.

**Comment by manoelcampos** [comment]
Hello @CharafeddineMechalikh 

Please provide me information on how to run the example in PureEdgeSim that presents this issue.
I'll take a look at it to see if there is any issue with CloudSim Plus.

**Comment by CharafeddineMechalikh** [comment]
hi, this issue is not related to a specific example.

you can launch the mainApplication directly, make sure you edit the CloudSim Plus version in pom.xml file, and also enable deep logging from settings/simulation_parameters.prop file, which enables the cloudsim plus logs.

**Comment by manoelcampos** [comment]
Hello @CharafeddineMechalikh 
Sorry for the delay. I cloned the latest version of PureEdgeSim and updated to CloudSim Plus 5.2.1 and ran the MainApplication. However, I couldn't see the issues you mentioned, even after enabling CloudSim Plus log. How did you check that Cloudlets aren't finishing?

Maybe the issue is related to #54 and #227 which I've just fixed. Try the new version and let me know if it worked. If not, please explain how you are checking the results.

**Comment by manoelcampos** [comment]
When you run the MainApplication, there is an overwhelming amount of simulations and results. This make very hard to find issues. Try to create a minimum simulation scenario that reproduces the issue and it will make it easier to find the cause.

I've checked lots of these messages below:

```
WARN  0.00: VmAllocationPolicySimple: No suitable host found for Vm 16 in Datacenter 3
WARN  0.00: VmAllocationPolicySimple: No suitable host found for Vm 17 in Datacenter 3

WARN  203.40: CloudletSchedulerSpaceShared: Cloudlet 505 requested 4000 MB of Ram but no amount is available.
WARN  203.40: CloudletSchedulerSpaceShared: Cloudlet 505 requested 300000 MB of Bandwidth but no amount is available.
WARN  277.73: CloudletSchedulerSpaceShared: Cloudlet 1389 requested 8000 MB of Ram but no amount is available.
WARN  277.73: CloudletSchedulerSpaceShared: Cloudlet 1389 requested 300000 MB of Bandwidth but no amount is available.
```

The first message happens for a bunch of consecutive VMs. I've checked the implementation of the `VmAllocationPolicySimple` changed from CloudSim Plus 4 to 5. The code from the former version is basically the same as in CloudSim. It uses an internal Map to keep track of available PEs for each Host, while in the later version, the number of available PEs is updated directly into each Host. This way, we don't need the Map inside the `VmAllocationPolicy` anymore.
That is why you need to streamline your example to make it easier to check if the issue is with your simulation scenario or CloudSim Plus. I suppose that the way CloudSim did to allocate Hosts to VMs using those maps, was causing oversubscription of Host's PEs, that is probably why you weren't getting warnings before.

Anyway, the `VmAllocationPolicySimple` implements a Worst Fit algorithm to allocate PMs to VMs. Such policies have a high computational complexity for large scale environments with thousands of Hosts. A more realistic approach would be the `VmAllocationPolicyFirstFit`.

About the last warnings, that happens when you use a `UtilizationModelFull` for Cloudlets's RAM and BW. That works fine for CPU, because of the preemption process. But we can't share RAM or BW. If a Cloudlets uses 100% of the RAM and there are other Cloudlets running into the same VM, the other Cloudlets will have no RAM to use. `UtilizationModelFull` doesn't make sense for RAM and BW. You should use a `UtilizationModelDynamic` instead.

**Comment by manoelcampos** [comment]
To check what I mentioned about the allocation of Hosts to VMs, try to change the Hosts to a large number and you may see the allocation failures will reduce.

**Comment by manoelcampos** [comment]
Hello @CharafeddineMechalikh 

I think I may have found the issue. Check [this repository](https://github.com/manoelcampos/cloudsim-cloudsimplus-allocation-issue) and its README for details.
I appreciate if you could give me some feedback.

**Comment by CharafeddineMechalikh** [comment]
Hi,
Sorry for the long reponse time. 
I will try all what you have mentioned tomorrow, and I'll get back to you as soon as possible.
Thank you very much for your hard work and support.
I appreciate your help.

**Comment by manoelcampos** [comment]
No problem. Looking forward to talking to you soon.

**Comment by CharafeddineMechalikh** [comment]
Hi,
so here is what I did (step by step), I followed all your comments to make sure that I don't miss anything:
1/ Edited the pom.xml file and updated from cloudsim plus 4.3.0 to 5.2.1 (and later to 5.2.2)
2/ Launched the MainApplication. at the first glance everything looks fine (the charts show that the CPUs are used). however, at the end of the simulation, the console show a negative value for execution time (Cloudlet.getActualCpuTime()):

SimLog- Tasks execution delay                                                   :         -1367 seconds   
SimLog- Average tasks execution delay                                     :               -1 seconds


3/ I changed the VM allocation policy to best fit, as you advised.

4/ I also changed the Ram and Bw utilization model to dynamic as you advised. and the warnings related to cloudlets have disappeared, but the execution time was still negative. the warnings that remained are all like this one:

[0;39m[31mWARN  5,00: VmAllocationPolicyBestFit: No suitable host found for Vm 76 in Datacenter 53

5/ I downgraded to 4.3.0 just to see if those warning will remain, and yes they remained (slightly changed):
[0;39m[1;31mERROR 4.000000000000002: VmSchedulerSpaceShared: Allocation of Vm 64/Broker 2 to Host 0/DC 43 failed due to lack of PEs. Required 8 PEs of 110000.0 MIPS.However, there are just 0 available PEs with the required MIPS.

But, the results are good:
SimLog- Tasks execution delay                                                   :           1466.2395 seconds
SimLog- Average tasks execution delay                                      :                1.0664 seconds

So, I conclude that those warnings are normal, and are not the reason for the negative execution time..??


6/ How did I, knew the tasks status?
because the tasks execution time was negative? I had to check the status of all cloudlets. so when I just printed the status within the method taskFailed() which checks if the task has been executed or not. the method is found within the simulation manager class

	public boolean taskFailed(Task task, int phase) {
		System.err.println(task.getId()+"  "+task.getStatus());
....

When using cloudsim plus 4.3.0, I  don't find the INEXE status. I only found these two:

392  SUCCESS
252  INSTANTIATED
973  INSTANTIATED
973  SUCCESS
252  SUCCESS
252  SUCCESS
772  SUCCESS
253  INSTANTIATED
253  SUCCESS
592  SUCCESS
592  SUCCESS

When I use the latest version I get these status:

178  INEXEC
179  SUCCESS
998  SUCCESS
118  INSTANTIATED
919  INSTANTIATED
919  INEXEC
118  INEXEC
918  SUCCESS
919  SUCCESS
118  SUCCESS
739  INSTANTIATED
738  SUCCESS
739  INEXEC
739  SUCCESS

So I concluded that the reason of that negative value is this "INEXE" status that only appears when I use a newer version (note that i used the best fit vm policy and the dynamic cpu model for Bw and Ram) 


7/ Now I tried your example entitled  "CloudSim vs CloudSim Plus Resource Allocation", which is very intresting. If I correctly inderstood, there is a bug in cloudsim plus 4.x.x which make it execute cloudlets on VMs even though they are bound to others.

I executed that example, however, the 5th Cloudlet status is INSTANTIATED not INEXE. which is not the same status I get when I use the a newer cloudsim plus version (> 4.4).

I also tried all 4.x versions this time. The 4.3.8 and below work fine, the 4.4.0 and above have the same issue. So we should compare the 4.3.8 to the 4.4.0 that should not be different that much so it should be easier to spot the origin of the issue.

To conclude, if that was a bug in CloudSim plus 4.x, why everything works fine with cloudsim plus 4.3.8 and below, but not with 4.4.0 and above (same INEXE status) ?

Until now this is what I have found.
 I will continue experimenting and see where this may take me.

Thank you for all this information, and support.

**Comment by manoelcampos** [comment]
> **2/** Launched the MainApplication. at the first glance everything looks fine (the charts show that the CPUs are used). however, at the end of the simulation, the console show a negative value for execution time (Cloudlet.getActualCpuTime()):
> 
> ```
> SimLog- Tasks execution delay: -1367 seconds   
> SimLog- Average tasks execution delay: -1 seconds
> ```

What are these values? The average between all submitted Cloudlets?

> 
> **3/** I changed the VM allocation policy to best fit, as you advised.

I said FirstFit, not BestFit. BestFit has exactly the same complexity as the Simple (WorstFit) policy.
Anyway, it works. It's just no realistic for large scale environments.

> **4/** I also changed the Ram and Bw utilization model to dynamic as you advised. and the warnings related to cloudlets have disappeared, 

Great.

> **5/** I downgraded to 4.3.0 just to see if those warning will remain, and yes they remained (slightly changed):
> 
> `ERROR 4.000000000000002: VmSchedulerSpaceShared: Allocation of Vm 64/Broker 2 to Host 0/DC 43 failed due to lack of PEs. Required 8 PEs of 110000.0 MIPS.However, there are just 0 available PEs with the required MIPS.`

Yeah, I removed these messages from the VmScheduler because the VmAllocationPolicy prints already prints them (despite showing fewer details).

> 
> But, the results are good:
> 
> ```
> SimLog- Tasks execution delay:  1466.2395 seconds
> SimLog- Average tasks execution delay:  1.0664 seconds
> ```

I suppose some Cloudlets are being moved to the finished list, without having some attributes (execution time, finish time).

> 
> So, I conclude that those warnings are normal, and are not the reason for the negative execution time..

Yeah, if you see than in both CloudSim Plus version, you just don't have enough Hosts to place all VMs. So, that is OK.

> 
> When using cloudsim plus 4.3.0, I don't find the INEXE status. I only found these two:
> 
> ```
> 392  SUCCESS
> 252  INSTANTIATED
> ```
> 
> When I use the latest version I get these status:
> 
> ```
> 178  INEXEC
> 179  SUCCESS
> 118  INSTANTIATED
> ```
> 
> So I concluded that the reason of that negative value is this "INEXE" status that only appears when I use a newer version 

Yes, you're right. The INEXEC status means some Cloudlets aren't finishing. That is why you are getting these negative values. How are you defining the length of your Cloudlets?
What are the possible values? It seems the processing of some Cloudlets are being missed. That may have to do with the Datacenter schedulingInterval and CloudSim minTimeBetweenEvents attributes, as I mentioned in issue #227. 
Therefore, it may be just a configuration issue. Check the MinTimeBetweenEventsExample.java for details.

What are the values of the attributes I mentioned?

> **7/** Now I tried your example entitled "CloudSim vs CloudSim Plus Resource Allocation", which is very intresting. If I correctly inderstood, there is a bug in cloudsim plus 4.x.x which make it execute cloudlets on VMs even though they are bound to others.
> 
> I executed that example, however, the 5th Cloudlet status is INSTANTIATED not INEXE. which is not the same status I get when I use the a newer cloudsim plus version (e.g. 5.2.2).
> 

This Status enum is inherited from CloudSim. The INSTANTIATED status is misleading. It just says the Cloudlet object was instantiated, but it doesn't mean it was created inside a VM. That is the default value. In CloudSim Plus 5, if the VM failed to be created, their Cloudlets won't be executed anywhere (as expected), but the status of such Cloudlets should be changed to FAILED. I've just opened a new issue for that in #231. INEXEC Cloudlets started to execute but were not finished for some reason (such as #227 as I mentioned above).

> **8/** After seeing your example, i had to try all the 4.x versions. The 4.3.8 and below work fine, while the 4.4.0 and above have the same issue.
> 
> If that was a bug in CloudSim plus 4.x, why everything works fine with cloudsim plus 4.3.8 and below, but not with 4.4.0 and above (same INEXE status) ?

Well, the bug is that Cloudlets bound to a VM that was not created are automatically moved to some other VM. In fact, your issue is different. Some Cloudlets aren't just been finished.

> 
> So we should compare the 4.3.8 to the 4.4.0 that should not be different that much so it should be easier to spot the origin of the issue, instead of comparing it to 5.2.2.
> Here is a [link to the comparison ](https://github.com/manoelcampos/cloudsim-plus/compare/v4.3.8...v4.4.0)

I've checked the differences in such versions. There are little related changes in DatacenterSimple, HostSimple,  CloudletSchedulerAbstract and VmSimple. Such changes were made exactly to fix a previous issue that was causing some Cloudltet to not finish. I remember specifically issue #163. So, this is a tricky issue.

> 
> In the comparison I can see that you have changed the line 715 in the Datacentersimple class ( the min time between events) could this be the reason? especially that I have seeing your [example ](https://github.com/manoelcampos/cloudsim-plus/blob/master/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/MinTimeBetweenEventsExample.java) that is talking about this.

It's related too. But I need to understand your scenario to find exactly what the problem is.
Therefore, I'll be waiting for answers to the questions I've made to try figuring out the issue.

> In this example you have mentioned :
> 
> > An example showing how the {@link Simulation#getMinTimeBetweenEvents()} may affect the processing
> > of events in your simulation.
> > This way, it may affect simulation accuracy, regarding the execution time of Cloudlets.
> 

Exactly, and Datacenter schedulingInterval too.

> Thank you for all this information, and support.

You're welcome.

**Comment by CharafeddineMechalikh** [comment]
I will answer the rest later, because I think I have found the issue.

check this code: 

in my CstomBroker.java class I implemented this in order to get notified when a cloudlet has been executed:

`@Override
	public void processEvent(final SimEvent ev) {
		super.processEvent(ev);
		switch (ev.getTag()) {
			case CloudSimTags.CLOUDLET_RETURN: // the task execution finished
				Task task = (Task) ev.getData();

// this always gives -1 when using a newer version ( > 4.4.0)
				System.out.println(task.getActualCpuTime());

				scheduleNow(simulationManager, SimulationManager.TRANSFER_RESULTS_TO_ORCH, task);
				break;
			default:
				break;
		}
	}`

As you can see I sent an event to the SimulationManager.

The simulation manager will process it as follows:

	```
case TRANSFER_RESULTS_TO_ORCH:
			// Transfer the results to the orchestrator
			sendResultsToOchestrator(task); // this is the task that I retrieved from the broker
			break;
```
that method is the following

`private void sendResultsToOchestrator(Task task) {
		if (taskFailed(task, 2))
			return;
		// If the task was offloaded
		if (task.getEdgeDevice().getId() != task.getVm().getHost().getDatacenter().getId()) {
			scheduleNow(networkModel, NetworkModel.SEND_RESULT_TO_ORCH, task);

		} else { // The task has been executed locally / no offloading
			scheduleNow(this, RESULT_RETURN_FINISHED, task);
		}
		// update tasks execution and waiting delays using the tasks retrieved from my custom broker
		simLog.getTasksExecutionInfos(task);
	}`

as you can see in the last line, I used the task retrieved from the broker to print the cpu time:
```
 SimLog- Tasks execution delay                                                   :               -1361 seconds
2020/03/18 22:32:00 - simulation time     610 (s) : SimLog- Average tasks execution delay                                           :                  -1 seconds
```

The printing results are all `-1` when I use a newer cloudsim plus version (> 4.4)
Thats why the total execution time is -1 x 1361 tasks = -1361 seconds
and the average is -1.
And when I use version 4.3.8 or lower, the results will be normal.

However, when I try to check the finished tasks time right before ending the simulation
```

			List<Task> finishedTasks = broker.getCloudletFinishedList();
// Show results and stop the simulation
			simLog.showIterationResults(finishedTasks);
              for(Task t: finishedTasks)
            	  System.err.println(t.getId()+"   "+ t.getStatus()+ "   "+ t.getActualCpuTime());
			// Terminate the simulation
			simulation.terminate();
			break;
```

the output will be : 
```
1381   SUCCESS   1.4199999999999946
301   SUCCESS   0.4199999999999946
241   SUCCESS   1.4199999999999946
1181   SUCCESS   1.4199999999999946
1380   SUCCESS   1.4199999999999946
60   SUCCESS   1.4199999999999946
1061   SUCCESS   1.4199999999999946
361   SUCCESS   0.4199999999999946
61   SUCCESS   1.4199999999999946
360   SUCCESS   0.4199999999999946
```



So I can just change my code and use the finished tasks list to get the execution time, and  everything will be okey.

But, I guess this is a bug. since in previous versions it works okey. 
so why does the cloudlet returned by the broker empty without any information?.

**Comment by CharafeddineMechalikh** [comment]
Yeah Issue solved,
I'm on cloudsim Plus version 5.2.2
I've created a custom  version of your class (CloudletSchedulerAbstract) 

when I use the following function as in 4.4.0 and newer versions:


```
  @Override
    public double updateProcessing(final double currentTime, final List<Double> mipsShare) {
        setCurrentMipsShare(mipsShare);

        if (isEmpty()) {
            setPreviousTime(currentTime);
            return Double.MAX_VALUE;
        }

       
        final double nextSimulationTime = updateCloudletsProcessing(currentTime);
        updateVmResourceAbsoluteUtilization(Ram.class);
        updateVmResourceAbsoluteUtilization(Bandwidth.class);
        
    >>>>>    addCloudletsToFinishedList(); // this line here
        moveNextCloudletsFromWaitingToExecList();
    
        setPreviousTime(currentTime);
        ((CloudSim)vm.getSimulation()).setLastCloudletProcessingUpdate(currentTime);

        return nextSimulationTime;
    }
```

I get negative values,
if I position that line above like this : 

`   addCloudletsToFinishedList();
        final double nextSimulationTime = updateCloudletsProcessing(currentTime);
        updateVmResourceAbsoluteUtilization(Ram.class);
        updateVmResourceAbsoluteUtilization(Bandwidth.class);
        
       
        moveNextCloudletsFromWaitingToExecList();
    `

Everything will be okey.

I followed the changes you have done here
https://github.com/manoelcampos/cloudsim-plus/compare/v4.3.8...v4.4.0#diff-e7b5b0219f9aae9f137ee890a8103519

So you can change it if it doesn't cause other issue.

**Comment by manoelcampos** [comment]
Hello @CharafeddineMechalikh 
Sorry for the long delay. These days have been crazy.

That makes total sense. Firstly we should update the processing of Cloudlets, then we have to add finished Cloudlets to the list.

>         double nextCloudletFinishTime = updateCloudletsProcessing(currentTime);
>         updateVmResourceAbsoluteUtilization(Ram.class);
>         updateVmResourceAbsoluteUtilization(Bandwidth.class);
>         nextCloudletFinishTime = Math.min(nextCloudletFinishTime, moveNextCloudletsFromWaitingToExecList(currentTime));
>         >>>>> addCloudletsToFinishedList();

I don't know if that will cause any side effects. There aren't enough tests for the framework, and I'm practically alone maintaining it. I'll update and check issues #163 and #227 again.

However, I have just a double about what you said below:

> 
> However, when I try to check the finished tasks time right before ending the simulation
> 
> ```
> List<Task> finishedTasks = broker.getCloudletFinishedList();
> ```
>
> the output will be :
> 1381   SUCCESS   1.4199999999999946
> 
> So I can just change my code and use the finished tasks list to get the execution time, and everything will be okey.
>

How were you getting the list of finished Cloudlets before?

**Comment by manoelcampos** [comment]
Could you please download the latest version from the dev branch and try again?
I checked the issues I mentioned and everything is ok with them.

The commit is f2289d57644dd9cb5fc0dddf15d8b7d0a0fb5ad6

**Comment by CharafeddineMechalikh** [comment]
Hi, 

> How were you getting the list of finished Cloudlets before?

```
List<Task> finishedTasks = broker.getCloudletFinishedList();

// If i check those values here, using that list, i get positive values (correct ones)

	// Terminate the simulation
			simulation.terminate();
```

so the issue is only when I use the broker to handle the event (when a task is finished)

here is my custom broker:
 
```

	public CustomBroker(CloudSim simulation) {
		super(simulation);
	}

	@Override
	public void processEvent(final SimEvent ev) {
		super.processEvent(ev);
		switch (ev.getTag()) {
			case CloudSimTags.CLOUDLET_RETURN: // the task execution finished 
				scheduleNow(simulationManager, SimulationManager.TRANSFER_RESULTS_TO_ORCH, ev.getData());
				break;
			default:
				break;
		}
	}

	public void setSimulationManager(SimulationManager simulationManager) {
		this.simulationManager = simulationManager;

	}

}
```
In this case the task is the ev.getData(). i f I check its values  i get -1 in newer cloudsim versions, and correct values with older versions (below 4.4).

To find the issue I tried to use a custom cloudletschuler, By changing just the location of that line, and it fixed it, as follows:

```
 double nextCloudletFinishTime = updateCloudletsProcessing(currentTime);
        updateVmResourceAbsoluteUtilization(Ram.class);
        updateVmResourceAbsoluteUtilization(Bandwidth.class);
        nextCloudletFinishTime = Math.min(nextCloudletFinishTime, moveNextCloudletsFromWaitingToExecList(currentTime));
      >>>>> addCloudletsToFinishedList();
        setPreviousTime(currentTime);
        vm.getSimulation().setLastCloudletProcessingUpdate(currentTime);
```

this way both of them will work, like in previous versions ( from the borker I get positive values, and from the finished tasks list i get positive values)

**Comment by CharafeddineMechalikh** [comment]
Hello again, sorry I had an issue related to dependencies, So I added them manually, which took me some time.
Yes it is working as expected.
Thank you very much for your support.

**Comment by manoelcampos** [comment]
Ok. Thanks for reporting and finding the source of the issue.
I'm merging to master and creating a new release today.
