### ISSUE TITLE
VM horizontal scaling (Auto Up/Down Scaling)

### ISSUE THREAD

**Issue by manoelcampos** [manoelcampos/cloudsim-plus#41]
# FEATURE:
Implement horizontal scaling of VMs by creating a VM snapshot to enable starting copies of such a VM from that snapshot when a given SLA metric is violated. This should be an auto scaling feature such as the [AWS Auto Scaling](https://aws.amazon.com/documentation/autoscaling/).

## Detailed information about how the feature should work
The horizontal scaling of VMs has to be performed, at least initially, considering the usage of some VM resource such as RAM, CPU or BW. As each Cloudlet has an UtilizationModel for each of these resources, to compute the total VM usage of a given resource it has to be just added up the utilization of all currently executing Cloudlets.

The horizontal auto scale mechanism has to be provided with a predicate that defines a lower utilization threshold (that may be composed of multiple conditions such as utilization of CPU and RAM) and a predicate that defines an upper utilization threshold, like it is used for PowerVmAllocationPolicyMigration.

The horizontal scale can act when dynamically created Cloudlets are submitted to the VM (see feature #43). By this way, Load Balancer defined inside the broker should use the upper utilization threshold to define when a new VM has to be created in order to balance the arrived Cloudlets between such VMs. 

It has to use the lower utilization threshold to define when a VM has to be destroyed. An under utilised VM will be destroyed just after all Cloudlets have finished. The Load Balancer won't just place new Cloudlets on such a VM.  At the current version, if a VM doesn't have Cloudlets anymore, it will just be destroyed when all VMs of the same broker finishes executing.

The Load Balancer has to be provided with a [Supplier](https://docs.oracle.com/javase/8/docs/api/java/util/function/Supplier.html) that knows how to create new VMs under request. The balancer has to maintain a map with the list of additional VMs that was created to balance the load of a given VM. By this way, there is not need to add a new attribute to relate a VM to another one.

When a VM is created from a snapshot, it must start with no running Cloudlets, simulating a cold boot. The Cloudlets that will execute inside such a new VM will be those ones dynamically created and submitted by the Load Balancer mechanism inside the Broker. 

## An example scenario where this feature should be used
It will enable starting new VMs in order to fulfil SLA requirements and balance workload.

## A brief explanation of why you think this feature is useful
It will allow to evaluate how SLA is fulfilled based on different load balancing policies.

**Comment by syu180** [comment]
Hi, i have 3 questions for cloudplus,
 1. for Horizontal VM Scaling (Auto Up/Down Scaling), do u think it is good to use this to simualte pods auto scaling in K8S?
 2. when i run this sample, that log showed when vm cpu overload, then will reqest 4 vms to be created, but after created, i found the new vms did not get any cloudets, and then get deduction of it, strange that meantime there are another 4 vms created, see log files below.
 3. which Google Group that i can subscribe to for further questions.


[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Sending Cloudlet 10 to Vm 2 in Host 2/DC 1.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Sending Cloudlet 11 to Vm 3 in Host 3/DC 1.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Sending Cloudlet 12 to Vm 4 in Host 4/DC 1.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Sending Cloudlet 13 to Vm 5 in Host 5/DC 1.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: All 4 waiting Cloudlets submitted to some VM.
[0;39m		Time  10.32: Vm 0 CPU Usage: 100.00% ( 2 vCPUs. Running Cloudlets: #02) Upper Threshold: 0.70 Is Overload: true
		Time  10.32: Vm 1 CPU Usage: 100.00% ( 2 vCPUs. Running Cloudlets: #03) Upper Threshold: 0.70 Is Overload: true
		Time  10.32: Vm 2 CPU Usage: 100.00% ( 2 vCPUs. Running Cloudlets: #02) Upper Threshold: 0.70 Is Overload: true
		Time  10.32: Vm 3 CPU Usage:   0.00% ( 2 vCPUs. Running Cloudlets: #00) Upper Threshold: 0.70 Is Overload: false
		Time  10.32: Vm 4 CPU Usage:   0.00% ( 2 vCPUs. Running Cloudlets: #00) Upper Threshold: 0.70 Is Overload: false
		Time  10.32: Vm 5 CPU Usage:   0.00% ( 2 vCPUs. Running Cloudlets: #00) Upper Threshold: 0.70 Is Overload: false
		Time  10.32: Vm 6 CPU Usage:   0.00% ( 2 vCPUs. Running Cloudlets: #00) Upper Threshold: 0.70 Is Overload: false
		Time  10.32: Vm 7 CPU Usage:   0.00% ( 2 vCPUs. Running Cloudlets: #00) Upper Threshold: 0.70 Is Overload: false
[31mWARN  15.32: CloudletSchedulerTimeShared: Cloudlet 8 requested 512 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
[0;39m[31mWARN  15.32: CloudletSchedulerTimeShared: Cloudlet 8 requested 1000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
[0;39m[34mINFO  15.32: HorizontalVmScalingSimpleVm 0: Requesting creation of Vm 8 to receive new Cloudlets in order to balance load of Vm 0. 0 CPU usage is 100.0%
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: List of 1 VMs submitted to the broker during simulation execution. VMs creation request sent to Datacenter.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Trying to create Vm 8 in DatacenterSimple1
[0;39m[31mWARN  15.32: CloudletSchedulerTimeShared: Cloudlet 5 requested 512 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
[0;39m[31mWARN  15.32: CloudletSchedulerTimeShared: Cloudlet 5 requested 1000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
[0;39m[31mWARN  15.32: CloudletSchedulerTimeShared: Cloudlet 9 requested 512 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
[0;39m[31mWARN  15.32: CloudletSchedulerTimeShared: Cloudlet 9 requested 1000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
[0;39m[34mINFO  15.32: HorizontalVmScalingSimpleVm 1: Requesting creation of Vm 9 to receive new Cloudlets in order to balance load of Vm 1. 1 CPU usage is 100.0%
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: List of 1 VMs submitted to the broker during simulation execution. VMs creation request sent to Datacenter.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Trying to create Vm 9 in DatacenterSimple1
[0;39m[31mWARN  15.32: CloudletSchedulerTimeShared: Cloudlet 6 requested 512 MB of Ram but no amount is available.. Using Virtual Memory, which delays Cloudlet processing.
[0;39m[31mWARN  15.32: CloudletSchedulerTimeShared: Cloudlet 6 requested 1000 Mbps of Bandwidth but no amount is available., which delays Cloudlet processing.
[0;39m[34mINFO  15.32: HorizontalVmScalingSimpleVm 2: Requesting creation of Vm 10 to receive new Cloudlets in order to balance load of Vm 2. 2 CPU usage is 100.0%
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: List of 1 VMs submitted to the broker during simulation execution. VMs creation request sent to Datacenter.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Trying to create Vm 10 in DatacenterSimple1
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Requesting Vm 4 destruction.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Requesting Vm 5 destruction.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Requesting Vm 6 destruction.
[0;39m[34mINFO  15.32: DatacenterBrokerSimple2: Requesting Vm 7 destruction.
[0;39m[34mINFO  15.32: VmAllocationPolicySimple: Vm 8 has been allocated to Host 8/DC 1
[0;39m[34mINFO  15.32: VmAllocationPolicySimple: Vm 9 has been allocated to Host 9/DC 1
[0;39m[34mINFO  15.32: VmAllocationPolicySimple: Vm 10 has been allocated to Host 10/DC 1
[0;39m[31mWARN  15.32: DatacenterSimple: Vm 4 destroyed on Host 4/DC 1. It had a total of 1 cloudlets (running + waiting). Some events may have been missed. You can try: (a) decreasing CloudSim's minTimeBetweenEvents and/or Datacenter's schedulingInterval attribute; (b) increasing broker's Vm destruction delay for idle VMs if you set it to zero; (c) defining Cloudlets with smaller length (your Datacenter's scheduling interval may be smaller than the time to finish some Cloudlets).
[0;39m[31mWARN  15.32: DatacenterSimple: Vm 5 destroyed on Host 5/DC 1. It had a total of 1 cloudlets (running + waiting). Some events may have been missed. You can try: (a) decreasing CloudSim's minTimeBetweenEvents and/or Datacenter's schedulingInterval attribute; (b) increasing broker's Vm destruction delay for idle VMs if you set it to zero; (c) defining Cloudlets with smaller length (your Datacenter's scheduling interval may be smaller than the time to finish some Cloudlets).
[0;39m[34mINFO  15.32: DatacenterSimple: Vm 6 destroyed on Host 6/DC 1. 
[0;39m[34mINFO  15.32: DatacenterSimple: Vm 7 destroyed on Host 7/DC 1.

**Comment by Farzanehabil** [comment]
hello
I want to implement an article that is about resource provisioning
Please send me your desire by email so that I can get help from you
email:linuxcafee2467@gmail.com
