### ISSUE TITLE
NetworkVmsExampleBagOfTasksApp and NetworkVmsExampleSimpleApp are freezing

### ISSUE THREAD

**Issue by manoelcampos** [manoelcampos/cloudsim-plus#85]
NetworkVmsExampleBagOfTasksApp and NetworkVmsExampleSimpleApp examples are freezing.

## Expected behavior
The examples should execute and show the results table.

## Actual behavior 
The examples keep in an infinite loop.

## Specifications like the version of the project, operating system or workload file used
Current development version.

**Comment by AbderrahmanL** [comment]
Hello
Is there any clue about the problem here? I did some debugging and it seems that even if the event queue has no elements, the future.isEmpty() still returns false !?

**Comment by manoelcampos** [comment]
I started to work on this feature a long time ago but I stopped. Yeah, the issue is with the NetworkCloudlet and the CloudletTasks. Probably a CloudletSendTask is sending messages that a CloudletReceiveTask is not receiving.

I'll try to follow your tips and let you know if I find the source of the issue. The PacketSchedulerSimple class is the one accountable to process network packets. It's used inside the CloudletSchedulerAbstract.updateCloudletProcessingAndPacketsDispatch method.

**Comment by AbderrahmanL** [comment]
Okey ill try and see from my side too.

**Comment by manoelcampos** [comment]
If you change the NetworkVmsExampleSimpleApp.NUMBER_OF_NETCLOUDLET_EXECUTION_TASKS to 1, it works. So the issue is when there is more than 1 CloudletExecutionTask for the same NetworkCloudlet. Now I need to check how to fix it.

**Comment by manoelcampos** [comment]
It's working for the NetworkVmsExampleSimpleApp, but not for the NetworkVmsExampleBagOfTasksApp yet.

**Comment by AbderrahmanL** [comment]
Please can can you tell me what was the problem ? I read the code in your
commit but i didn't get what change  exactly fixed it

Thank you!

**Comment by manoelcampos** [comment]
Yeah, I made a lot of changes not related to the issue (most of them just refactoring). This is a bad practice 😢, but since I'm always in a rush, I don't have time to go back and make such changes afterward (and usually I will not remember where I need to refactor).  Basically, the issue was caused because the number of executed MIPS of each CloudletExecutionTask was not being updated correctly for the second task, this way that task never finished.

Since I was always working alone, it was never a problem. I'll try to do it right next time. I included some comments in the commit [here](https://github.com/manoelcampos/cloudsim-plus/commit/fc822010857e45998b10b4b55616829f454eedfa#diff-5b03527fc7e0c78e0c5ba5332985a820R85).

**Comment by AbderrahmanL** [comment]
Thank you! Don't worry ill tell you whenever i don't get something.

**Comment by manoelcampos** [comment]
Just closed the issue, this time reducing the number of changes.
The issue was just with the `NetworkVmsExampleBagOfTasksApp`. 
Check comments at 270bac277671b95b4363213b8811f0b7bfb09b7d

**Comment by AbderrahmanL** [comment]
Hello

I have found something a bit odd, receivePackets in the
PacketsSchedulersimple assumes that the current cloudlet is the destination
cloudlet without verifying so, as a result if we have cloudlets A in a host
X that is sending a msg to cloudlet B in another host Y, and B doesn't have
receive task, but a cloudlet C in host Y too does have the a receive task,
C will receive the messages instead.

First i recommand that the parameter of receivePackets should not be named
"sourceCloudlet" it should be something like "candidateReceiverCloudlet" or
something that means the same since this is what it is actually, as well as
the getSourceVm method in the Task class it should be just getContainingVm
since "source" is especially deceiving in this whole messaging context (in
getPacketsSentToGivenTask for example).

So before logging to DEGUB that this candidate has received the cloudlet it
should be verified that the id of this "candidateReceiverCloudlet" is
actulally the destination cloudlet's id, this can be done in the
getPacketsSentToGivenTask, by comparing ids of cloudlets in addition to
Vms's.

**Comment by manoelcampos** [comment]
I'll need a couple of days to take a look at this issue because I'm working with issue #24 for my thesis experiments. 

Thanks for reporting.

**Comment by AbderrahmanL** [comment]
Okey good luck with your thesis!

**Comment by manoelcampos** [comment]
The issue #24 is closed and moves CloudSim Plus to 3.0 release. Despite simple, it changed a huge number of classes to provide a feature that will be extremely useful. Check the issue link for details. 

Since there is a large number of changes to replace the Log class by Logback library, as soon as you update your fork, easier it will be. I'll take a look at the reported issue on the next couple of days.

**Comment by AbderrahmanL** [comment]
Thank you and congrats!

**Comment by AbderrahmanL** [comment]
What i said is a result i knew that the method will be called for every
cloudlet still what i discribed is the result, even if the method will be
called for the cloudlet B and B is the destination cloudlet, C will receive
the packets in the end since it has a receiver task and B has none. I will
recheck and next time ill try to be more clear with my explanation.

--Thanks

**Comment by manoelcampos** [comment]
I didn't get what you mean this time.
Even if Cloudlet B doesn't have a receiver task and Cloudlet C does, the method getPacketsSentToCloudlet makes sure that just packets targeting the correct Cloudlet are delivered (after the change you proposed).

If you check the example of the first link, it keeps in an infinite loop because Cloudlet C just keeps waiting for packets that aren't sent. Packets sent to Cloudlet B are received by the Host (as you can see in the log). However, since the Cloudlet B doesn't have a receive task, the packets are not delivered.

This way, if there is an issue, it's not clear to me what it is.
